# FUCKER
- fucker
- fuckers
- fucka
- fuckas
- fcuker
- fcukers
- fuker
- fukers
- motherfucker
- mothafucka
- motherfucka
- mothafucker
- mother fucker
- motha fucka
- mother fucka
- motha fucker
- fucktard
# FAG
- fag
- fags
- faggot
- faggots
- faggoty
- faggotty
- fagoty
- fagotty
- fagity
- fagitty
# CUNT
- cunt
- cunts
- cuntish
- cunty
# ASS
- ass
- asses
- arse
- arses
- asshole
- assholes
- ashole
- asholes
- ahole
- aholes
- ash0le
- ash0les
- azzhole
- azzholes
- arschloch
- arschlochs
- arschlocher
- assholish
- assholy
- assholey