- stab
- kill
- beat up
- beat the shit out of
- beat the fuck out of
- fuck up
- murder
- murdered
- genocide
- shoot him
- shoot her
- shoot it
- shoot me
- shoot us
- shoot them
- shot him
- shot her
- shot it
- shot me
- shot us
- shot them